### PR TITLE
update to be compatible with SS3.2+

### PR DESCRIPTION
**Pull request by wernerkrauss**
also updating libphonenumber requirement to latest 7.x

### CODE REVIEW

**Comment by xini** [comment]
Hi Werner,
Thanks for the PR. I do get the update of libphonenumber. But why the other changes? The field works perfectly fine with SS 3.2+. no?
Cheers, Flo

**Comment by xini** [comment]
also, did you try to upgrade libphonenumber-for-php to version 8?

**Comment by wernerkrauss** [comment]
hmm, could be we have different form templates it's cause we use BootstrapForms module. Didn't think of that, sorry. Maybe we should make the selector configurable then, like in #3 ?

I didn't try to update to libphonenumber v8.

**Comment by xini** [comment]
ok no worries. I'm happy to change the selector, it works either way. But I'll keep the SS requirement at 3.1.

**Comment by xini** [comment]
I have just tagged v 2.0.0 with your changes. Thank you very much!

**Pull request merged**
